import type { GameEvent } from "../types";

export const initialEvents: GameEvent[] = [
  {
    id: 1,
    name: "Battle Pass - Loop",
    doc: "",
    patch: "Patch 2",
    dateStart: "12/Jan/26",
    dateEnd: "",
    loop: true,
    type: "Always",
    unlockAt: "Chapter 2",
    durationStr: "14d",
    intervalStr: "0m",
    sandboxName: "battle_pass_loop_test",
    realName: "battle_pass_loop",
    remoteConfigStr: '{"rule":{"timeStart":20260112000001,"duration":1209598,"seasonStart":2,"intervals":[2],"dataIds":[0]},"overrideSeason":{"timeStart":20251223235959,"timeEnd":20260111235959,"season":1,"dataId":0}}',
    iaps: "com.thp020.stickman.casual.war.game.season_pass",
    currentSeason: ""
  },
  {
    id: 2,
    name: "Battle Pass Stamina",
    doc: "",
    patch: "Patch 3",
    dateStart: "16/Feb/26",
    dateEnd: "",
    loop: true,
    type: "Always",
    unlockAt: "Chapter 3",
    durationStr: "14d",
    intervalStr: "5m",
    sandboxName: "battle_pass_jack_pot_test",
    realName: "battle_pass_jack_pot",
    remoteConfigStr: '{"rule":{"timeStart":20260216000001,"duration":1209300,"seasonStart":1,"intervals":[300],"dataIds":[0]}}',
    iaps: "com.thp020.stickman.casual.war.game.battle_pass_jack_pot",
    currentSeason: ""
  },
  {
    id: 3,
    name: "Chest Secret",
    doc: "",
    patch: "Patch 3",
    dateStart: "13/Feb/26",
    dateEnd: "",
    loop: true,
    type: "Always",
    unlockAt: "Always",
    durationStr: "3d",
    intervalStr: "15m",
    sandboxName: "chest_secret_test",
    realName: "chest_secret",
    remoteConfigStr: '{"rule":{"timeStart":20260213000001,"duration":258300,"seasonStart":1,"intervals":[900],"dataIds":[3,4,5,6]}}',
    iaps: "Không có IAP",
    currentSeason: ""
  },
  {
    id: 4,
    name: "Event Growth - Pet (Tower)",
    doc: "",
    patch: "Patch 3",
    dateStart: "16/Feb/26",
    dateEnd: "",
    loop: true,
    type: "Growth",
    unlockAt: "Chapter 10",
    durationStr: "7d",
    intervalStr: "14d",
    sandboxName: "event_limited_pet_egg_test",
    realName: "event_limited_pet_egg",
    remoteConfigStr: '{"rule":{"timeStart":20260216000001,"duration":604800,"seasonStart":1,"intervals":[1209600],"dataIds":[0]}}',
    iaps: "com.thp020.stickman.casual.war.game.grow_pack_pet_1 ->5",
    currentSeason: ""
  },
  {
    id: 5,
    name: "Event Growth - Chest",
    doc: "",
    patch: "Patch 3",
    dateStart: "23/Feb/26",
    dateEnd: "",
    loop: true,
    type: "Growth",
    unlockAt: "Chapter 10",
    durationStr: "7d",
    intervalStr: "14d",
    sandboxName: "event_limited_collectible_chest_test",
    realName: "event_limited_collectible_chest",
    remoteConfigStr: '{"rule":{"timeStart":20260223000001,"duration":604800,"seasonStart":1,"intervals":[1209600],"dataIds":[0]}}',
    iaps: "com.thp020.stickman.casual.war.game.grow_pack_chest_1 ->5",
    currentSeason: ""
  },
  {
    id: 6,
    name: "Event Growth - Pet Build (Tower Build)",
    doc: "",
    patch: "Patch 3",
    dateStart: "2/Mar/26",
    dateEnd: "",
    loop: true,
    type: "Growth",
    unlockAt: "Chapter 10",
    durationStr: "7d",
    intervalStr: "14d",
    sandboxName: "event_limited_pet_build_test",
    realName: "event_limited_pet_build",
    remoteConfigStr: '{"rule":{"timeStart":20260302000001,"duration":604800,"seasonStart":1,"intervals":[1209600],"dataIds":[0]}}',
    iaps: "com.thp020.stickman.casual.war.game.grow_pack_build_1 ->7",
    currentSeason: ""
  },
  {
    id: 7,
    name: "Event Growth - Glow (Drone)",
    doc: "",
    patch: "Patch 3",
    dateStart: "23/Feb/26",
    dateEnd: "",
    loop: true,
    type: "Growth",
    unlockAt: "Chapter 10",
    durationStr: "2d",
    intervalStr: "19d",
    sandboxName: "event_limited_glow_w_growth_test",
    realName: "event_limited_glow_w_growth",
    remoteConfigStr: '{"rule":{"timeStart":20260223000001,"duration":172800,"seasonStart":1,"intervals":[1641600],"dataIds":[0]}}',
    iaps: "com.thp020.stickman.casual.war.game.grow_pack_glow_1 ->5",
    currentSeason: ""
  },
  {
    id: 8,
    name: "Event Stamina Loại 1 - 3 Day (Collection)",
    doc: "",
    patch: "Patch 3",
    dateStart: "16/Feb/26",
    dateEnd: "",
    loop: true,
    type: "Always",
    unlockAt: "Chapter 3",
    durationStr: "3d, 3d",
    intervalStr: "2d",
    sandboxName: "event_treasure_ranking_test",
    realName: "event_treasure_ranking",
    remoteConfigStr: '{"rule":{"timeStart":20260216000001,"duration":259198,"seasonStart":1,"intervals":[2,172802],"dataIds":[0]}}',
    iaps: "Không có IAP",
    currentSeason: ""
  },
  {
    id: 9,
    name: "Event Stamina Loại 2 - 2 Day",
    doc: "",
    patch: "Patch 3",
    dateStart: "22/Feb/26",
    dateEnd: "",
    loop: true,
    type: "Always",
    unlockAt: "Chapter 3",
    durationStr: "2d",
    intervalStr: "6d",
    sandboxName: "event_jackpot_test",
    realName: "event_jackpot",
    remoteConfigStr: '{"rule":{"timeStart":20260222000001,"duration":172798,"seasonStart":1,"intervals":[518402],"dataIds":[0]}}',
    iaps: "Không có IAP",
    currentSeason: ""
  },
  {
    id: 10,
    name: "Event Weekend Slot Machine",
    doc: "",
    patch: "Patch 3",
    dateStart: "14/Feb/26",
    dateEnd: "",
    loop: true,
    type: "Weekend",
    unlockAt: "Chapter 2",
    durationStr: "2d",
    intervalStr: "5d",
    sandboxName: "event_slot_machine_test",
    realName: "event_slot_machine",
    remoteConfigStr: '{"rule":{"timeStart":20260214000001,"duration":172800,"seasonStart":1,"intervals":[432000],"dataIds":[0]}}',
    iaps: "com.thp020.stickman.casual.war.game.slot_machine_1 ->6",
    currentSeason: ""
  },
  {
    id: 11,
    name: "Adventure Event - Season Loop",
    doc: "",
    patch: "Patch 3",
    dateStart: "16/Feb/26",
    dateEnd: "",
    loop: true,
    type: "Hero Exclusive",
    unlockAt: "Chapter 5",
    durationStr: "7d",
    intervalStr: "0m",
    sandboxName: "event_adventure_test",
    realName: "event_adventure",
    remoteConfigStr: '{"rule":{"timeStart":20260216000001,"duration":604798,"seasonStart":1,"intervals":[2],"dataIds":[0,1,2]}}',
    iaps: "Data 1: com.thp020.stickman.casual.war.game.event_adventure_1 ->6; Data 2: com.thp020.stickman.casual.war.game.event_adventure_7 ->12; Data 3: com.thp020.stickman.casual.war.game.event_adventure_15 ->21",
    currentSeason: ""
  },
  {
    id: 12,
    name: "Battle Pass Hero",
    doc: "",
    patch: "Patch 6",
    dateStart: "27/Apr/26",
    dateEnd: "",
    loop: true,
    type: "Hero Exclusive",
    unlockAt: "Chapter 5",
    durationStr: "14d",
    intervalStr: "7d",
    sandboxName: "hero_pass_test",
    realName: "hero_pass",
    remoteConfigStr: '{"rule":{"timeStart":20260427000001,"duration":1209600,"seasonStart":4,"intervals":[604800],"dataIds":[0]}}',
    iaps: "com.thp020.stickman.casual.war.game.hero_pass",
    currentSeason: ""
  },
  {
    id: 13,
    name: "Seasonal Event - Dice Event",
    doc: "",
    patch: "Patch 5",
    dateStart: "30/Oct/25",
    dateEnd: "12/Nov/25",
    loop: true,
    type: "New Minigame",
    unlockAt: "Chapter 10",
    durationStr: "14d",
    intervalStr: "0m",
    sandboxName: "event_dice_test",
    realName: "event_dice",
    remoteConfigStr: '{"manualSeason":[{"timeStart":20260422000001,"timeEnd":20260508000001,"season":1,"dataId":0,"lockedDuration":172800}]}',
    iaps: "com.thp020.stickman.casual.war.game.event_dice_pack_1->6; com.thp020.stickman.casual.war.game.event_dice_pass",
    currentSeason: ""
  },
  {
    id: 14,
    name: "Seasonal Event - Plant Event",
    doc: "",
    patch: "Patch 5",
    dateStart: "",
    dateEnd: "",
    loop: true,
    type: "New Minigame",
    unlockAt: "Chapter 10",
    durationStr: "14d",
    intervalStr: "0m",
    sandboxName: "event_plant_harvest_test",
    realName: "event_plant_harvest",
    remoteConfigStr: '{"manualSeason":[{"timeStart":20260515000001,"timeEnd":20260529000001,"season":1,"dataId":0,"lockedDuration":172800}]}',
    iaps: "com.thp020.stickman.casual.war.game.plant_harvest_pack_1->6; com.thp020.stickman.casual.war.game.event_plant_harvest_pass",
    currentSeason: ""
  },
  {
    id: 15,
    name: "Seasonal Event - Fishing Event",
    doc: "",
    patch: "Patch 5",
    dateStart: "",
    dateEnd: "",
    loop: true,
    type: "New Minigame",
    unlockAt: "Chapter 10",
    durationStr: "14d",
    intervalStr: "0m",
    sandboxName: "event_fishing_test",
    realName: "event_fishing",
    remoteConfigStr: '{"manualSeason":[{"timeStart":20260610000001,"timeEnd":20260624000001,"season":1,"dataId":0,"lockedDuration":172800}]}',
    iaps: "com.thp020.stickman.casual.war.game.event_fishing_pack_1->6; com.thp020.stickman.casual.war.game.event_fishing_pass",
    currentSeason: ""
  },
  {
    id: 16,
    name: "Seasonal Event - Bingo Event",
    doc: "",
    patch: "Patch 6",
    dateStart: "",
    dateEnd: "",
    loop: true,
    type: "New Minigame",
    unlockAt: "Chapter 10",
    durationStr: "14d",
    intervalStr: "0m",
    sandboxName: "event_bingo_test",
    realName: "event_bingo",
    remoteConfigStr: '{"manualSeason":[{"timeStart":20260705000001,"timeEnd":20260719000001,"season":1,"dataId":0,"lockedDuration":172800}]}',
    iaps: "com.thp020.stickman.casual.war.game.event_mining_area_pack_1->6; com.thp020.stickman.casual.war.game.event_mining_area_pass",
    currentSeason: ""
  },
  {
    id: 17,
    name: "Seasonal Event - Mining Event",
    doc: "",
    patch: "Patch 6",
    dateStart: "",
    dateEnd: "",
    loop: true,
    type: "New Minigame",
    unlockAt: "Chapter 10",
    durationStr: "14d",
    intervalStr: "0m",
    sandboxName: "event_mining_area_test",
    realName: "event_mining_area",
    remoteConfigStr: '{"manualSeason":[{"timeStart":20260801000001,"timeEnd":20260815000001,"season":1,"dataId":0,"lockedDuration":172800}]}',
    iaps: "com.thp020.stickman.casual.war.game.event_mining_area_pack_1->6; com.thp020.stickman.casual.war.game.event_mining_area_pass",
    currentSeason: ""
  }
];
